apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: openframe-management
build:
  artifacts:
    - image: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-management
      context: ../../../
      sync: 
        manual:
          - src: "**/*"
            dest: "/app"
      docker:
        dockerfile: openframe/services/openframe-management/Dockerfile
        buildArgs:
          GITHUB_ACTOR: "{{.GITHUB_ACTOR}}"
          GITHUB_TOKEN: "{{.GITHUB_TOKEN}}"
      hooks:
        before:
          - command: [ "mvn", "clean", "package", "-DskipTests"]
  local:
    useDockerCLI: false
    useBuildkit: true
    push: false
manifests:
  helm:
    releases:
      - name: openframe-management
        chartPath: ../../../manifests/microservices/openframe-management
        valuesFiles:
          - ../../../manifests/microservices/openframe-management/values.yaml
        # setValues:
