name: Sign Windows package
description: Sign Windows executable using Azure Trusted Signing
inputs:
  azure_tenant_id:
    description: 'Azure AD tenant ID'
    required: true
  azure_client_id:
    description: 'Azure AD application (client) ID'
    required: true
  azure_client_secret:
    description: 'Azure AD client secret'
    required: true
  signing_endpoint:
    description: 'Azure Trusted Signing endpoint URL'
    required: true
  code_signing_account_name:
    description: 'Azure Trusted Signing account name'
    required: true
  certificate_profile_name:
    description: 'Certificate profile name'
    required: true
  name:
    description: 'Client name (e.g. "openframe-client"). Used for binary path resolution.'
    required: true
  target_path:
    description: 'Cargo target directory (e.g. ./clients/openframe-client/target)'
    required: true
  target:
    description: 'Rust build target (e.g. x86_64-pc-windows-msvc)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup and verify binary path
      shell: pwsh
      run: |
        $ArtifactPath = "${{ github.workspace }}/${{ inputs.target_path }}/${{ inputs.target }}/release/${{ inputs.name }}.exe"

        if (-not (Test-Path $ArtifactPath)) {
          Write-Error "Binary not found at: $ArtifactPath"
          exit 1
        }

        Write-Host "Binary to sign: $ArtifactPath"
        echo "ARTIFACT_PATH=$ArtifactPath" >> $env:GITHUB_ENV

    - name: Sign Windows Executable
      uses: azure/trusted-signing-action@v0.5.0
      with:
        azure-tenant-id: ${{ inputs.azure_tenant_id }}
        azure-client-id: ${{ inputs.azure_client_id }}
        azure-client-secret: ${{ inputs.azure_client_secret }}
        endpoint: ${{ inputs.signing_endpoint }}
        trusted-signing-account-name: ${{ inputs.code_signing_account_name }}
        certificate-profile-name: ${{ inputs.certificate_profile_name }}
        files: ${{ env.ARTIFACT_PATH }}
        file-digest: SHA256
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256

    - name: Verify Signature
      shell: pwsh
      run: |
        Write-Host "Verifying signature for: $env:ARTIFACT_PATH"
        $sig = Get-AuthenticodeSignature -FilePath $env:ARTIFACT_PATH

        Write-Host "  Status: $($sig.Status)"
        Write-Host "  Status Message: $($sig.StatusMessage)"

        if ($sig.SignerCertificate) {
          Write-Host "  Signer: $($sig.SignerCertificate.Subject)"
          Write-Host "  Issuer: $($sig.SignerCertificate.Issuer)"
          Write-Host "  Thumbprint: $($sig.SignerCertificate.Thumbprint)"
        }

        if ($sig.TimeStamperCertificate) {
          Write-Host "  Timestamped: Yes"
          Write-Host "  Timestamp Authority: $($sig.TimeStamperCertificate.Subject)"
        }

        if ($sig.Status -ne "Valid") {
          Write-Error "Signature verification failed for $env:ARTIFACT_PATH"
          Write-Error "Status: $($sig.Status)"
          Write-Error "Message: $($sig.StatusMessage)"
          exit 1
        }

        Write-Host "Signature verified successfully!"
