name: Setup Telepresence
description: Install Telepresence and connect to cluster

runs:
  using: composite
  steps:
    - name: Install Telepresence
      shell: bash
      run: |
        sudo curl -fL https://app.getambassador.io/download/tel2oss/releases/download/v2.20.2/telepresence-linux-amd64 -o /usr/local/bin/telepresence
        sudo chmod a+x /usr/local/bin/telepresence
        echo "✅ Telepresence installed"

    - name: Connect to cluster with Telepresence
      shell: bash
      run: |
        telepresence connect
        echo "✅ Connected to cluster"

